name: Run Tests

on:
  push:
    branches:
      - dev
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: |
          docker build -t redjango_app .

      - name: Run tests
        env:
          DJANGO_SETTINGS_MODULE: "config.settings.dev"
          DB_NAME_DEV: ${{ secrets.DB_NAME_DEV }}
          DB_USER_DEV: ${{ secrets.DB_USER_DEV }}
          DB_PASSWORD_DEV: ${{ secrets.DB_PASSWORD_DEV }}
          DB_HOST_DEV: ${{ secrets.DB_HOST_DEV }}
          DB_PORT: ${{ secrets.DB_PORT }}
        run: |
          echo "Verificando vari√°veis de ambiente:"
          echo "DB_NAME_DEV: $DB_NAME_DEV"
          docker run \
            -e DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE \
            -e DB_NAME_DEV=$DB_NAME_DEV \
            -e DB_USER_DEV=$DB_USER_DEV \
            -e DB_PASSWORD_DEV=$DB_PASSWORD_DEV \
            -e DB_HOST_DEV=$DB_HOST_DEV \
            -e DB_PORT=$DB_PORT \
            --rm redjango_app python redjango/manage.py test
